trigger:
  branches:
    include:
      - main
      - develop
      - rc/*
      - patch/*

pr:
  branches:
    include:
      - main
      - develop
      - rc/*
      - patch/*

parameters:
  - name: forceBuild
    displayName: Force build Python artifact and push to feed
    type: boolean
    default: false

variables:
  tag: "$(Build.BuildId)"
  branch: "$(Build.SourceBranchName)"
  repoName: "howler_client"
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPrBranch: $[eq(variables['Build.SourceBranchName'], 'merge')]
  pythonVersion: "3.9"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: test
    jobs:
      - job: Run_Python_Test
        strategy:
          matrix:
            python3_9:
              python.version: "3.9"

        steps:
          - task: UsePythonVersion@0
            displayName: Set Python Version
            inputs:
              versionSpec: "3.9"
          - script: |
              cd python
              python -m venv venv
              . ./venv/bin/activate
              python -m pip install --upgrade pip
              python -m pip install --no-cache-dir -e .

              python -m pip install --no-cache-dir -r test/requirements.txt
            displayName: Install howler-client
            workingDirectory: $(Pipeline.Workspace)/s
          - script: |
              cd python
              . ./venv/bin/activate
              python -m howler.app &
              pytest -rsx -vv test/unit
            workingDirectory: $(Pipeline.Workspace)/s
            displayName: Test
